@Outbox.API_HostAddress = https://localhost:7057

###

POST {{Outbox.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "customerId": 123,
  "productId": 456,
  "quantity": 5
}

###

GET {{Outbox.API_HostAddress}}/api/orders/7c1df4f3-2596-4966-bc8a-e838fde1e2f1

###
